Fix undefined method `helper_method`
When gtm_on_rails is used with the gem using ActionController::API,
undefined method `helper_method` error occurs.

initialize_data_layer.rb:12:in `block in <module:InitializeDataLayer>': undefined method `helper_method' for ActionController::API:Class (NoMethodError)